const DEFAULT=[{title:"天命所歸典禮曲",artist:"皇家音樂廳",youtube:"https://www.youtube.com/watch?v=nJFxOGmXo3k"}];
let songs=[],player=null,ready=false,current=-1;
const $=s=>document.querySelector(s);
function vid(u){try{const x=new URL(u);return x.hostname.includes("youtu.be")?x.pathname.slice(1).split("/")[0]:x.searchParams.get("v")||((x.pathname.match(/\/embed\/([^/]+)/)||[])[1]||"")}catch{return""}}
async function load(){try{const r=await fetch("songs.json?v="+Date.now(),{cache:"no-store"});const x=await r.json();songs=Array.isArray(x)&&x.length?x:DEFAULT}catch{songs=DEFAULT}}
function render(){count.textContent=songs.length+" 首";playlist.innerHTML="";songs.forEach((s,i)=>{const b=document.createElement("button");b.className="track "+(i===current?"active":"");b.innerHTML='<img src="https://i.ytimg.com/vi/'+encodeURIComponent(vid(s.youtube))+'/hqdefault.jpg"><span><div class="track-title"></div><div class="track-meta"></div></span>';b.querySelector(".track-title").textContent=s.title;b.querySelector(".track-meta").textContent=s.artist||"皇家音樂廳";b.onclick=()=>play(i);playlist.appendChild(b)})}
function play(i){const s=songs[i],id=vid(s.youtube);if(!id)return;current=i;title.textContent=s.title;artist.textContent=s.artist||"皇家音樂廳";soundNote.textContent="♪ 正在演奏";render();if(ready){player.loadVideoById(id);player.playVideo()}else window.pending=id}
function make(){if(player)return;const id=window.pending||vid(songs[0]?.youtube||"");if(!id)return;player=new YT.Player("player",{videoId:id,playerVars:{playsinline:1,controls:0,rel:0},events:{onReady:e=>{ready=true;if(current>=0){e.target.loadVideoById(id);e.target.playVideo()}}}})}
window.onYouTubeIframeAPIReady=make;
for(let i=0;i<26;i++){const e=document.createElement("span");e.className="note";e.textContent=["♪","♫","♩","·","◦"][i%5];e.style.left=(8+Math.random()*84)+"%";e.style.top=(10+Math.random()*78)+"%";e.style.setProperty("--x",(Math.random()*70-35)+"px");e.style.setProperty("--dur",(2.4+Math.random()*2.8)+"s");e.style.setProperty("--delay",(Math.random()*3)+"s");document.querySelector("#noteField").appendChild(e)}
(async()=>{await load();render();const s=document.createElement("script");s.src="https://www.youtube.com/iframe_api";document.head.appendChild(s)})();